---
# tasks file for ansible-role-apt

- name: Update package cache before key, repo, or packages tasks.
  include_tasks: "update-apt-cache.yml"

- name: Include apt key management tasks.
  include_tasks: "manage-apt-keys.yml"

- name: Include apt repository management tasks.
  include_tasks: "manage-apt-repositories.yml"

- name: Include apt package management tasks.
  include_tasks: "manage-apt-packages.yml"
